services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mlflow
  mlflow:
    build: ./mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - "5001:5000"
    networks:
      - rschallenge_network
  db:
    build: ./db
    ports:
      - "3306:3306"
    volumes:
      - .mysql-data:/var/lib/mysql
    networks:
      - rschallenge_network
  notebook:
    build: ./notebook
    ports:
      - "8888:8888"
    networks:
      - rschallenge_network

networks:
  rschallenge_network:
    driver: bridge